# Generated by Django 5.1.6 on 2025-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_distribue',
            field=models.BooleanField(default=False),
        ),
    ]
