# Generated by Django 5.2.4 on 2025-08-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
