# Generated by Django 5.1.6 on 2025-08-11 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_transaction_is_distribue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='distributeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_distribuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
