# Generated by Django 5.2.4 on 2025-08-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_delete_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_envoyee', models.CharField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('CAD', 'Dollar Canadien'), ('SAR', 'Riyal Saoudien'), ('GNF', 'Franc Guinéen')], max_length=3)),
                ('montant_envoye', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise_recue', models.CharField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('CAD', 'Dollar Canadien'), ('SAR', 'Riyal Saoudien'), ('GNF', 'Franc Guinéen')], max_length=3)),
                ('pourcentage_gain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_converti', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
