# Generated by Django 5.2.4 on 2025-08-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='montant_remis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
