# Generated by Django 5.1.6 on 2025-08-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_transaction_distributeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_distribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_envoyees', to=settings.AUTH_USER_MODEL),
        ),
    ]
