# Generated by Django 5.2.4 on 2025-08-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_transaction_gain_transaction_montant_remis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gain',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gain_transfert',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_converti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_remis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
