# Generated by Django 5.2.4 on 2025-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_remove_transaction_gain_transaction_gain_transfert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gain_transfert',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_converti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_remis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
