# Generated by Django 5.1.6 on 2025-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gain_transfert',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_converti',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant_remis',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
