# Generated by Django 5.1.6 on 2025-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_delete_exchangerate_alter_transaction_gain_transfert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiaire_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
